# Project information
site_name: system-design-multilang
site_url: https://github.com/diptu/system-design-multilang
site_author: Nazmul Alam
site_description: >-
  My digital laboratory for mastering system Design through regular practice in multiple programming language.

# Repository
repo_name: diptu/system-design-multilang
repo_url: https://github.com/diptu/system-design-multilang

# Copyright
copyright: Copyright &copy; 2025 - 2025 Nazmul Alam

# Configuration
theme:
  name: material
  # name: readthedocs

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - user guide: ./system-desing/getting-started.md
  - System Design:
      - Topics : ./system-desing/index.md
  - License: LICENSE.md